drop
  table if exists movimientos cascade;
drop
   table if exists clientes cascade;
drop
  table if exists cuentas cascade;

create table clientes (
  cliente_id bigint generated by default as identity,
  edad integer,
  status boolean,
  direccion varchar(255),
  genero varchar(255),
  identificacion varchar(255),
  nombre varchar(255),
  password varchar(255),
  telefono varchar(255),
  primary key (cliente_id)
);

create table cuentas (
  cuenta_id bigint generated by default as identity,
  saldo_inicial numeric(38, 2),
  status boolean,
  cliente_id bigint unique,
  foreign key (cliente_id) references clientes(cliente_id),
  numero_de_cuenta bigint,
  account_type varchar(255),
  primary key (cuenta_id)
);

create table movimientos (
  movimiento_id bigint generated by default as identity,
  fecha date,
  valor numeric(38, 2),
  cuenta_id bigint,
  foreign key (cuenta_id) references cuentas(cuenta_id),
  tipo_de_movimiento varchar(255),
  primary key (movimiento_id)
);

insert into CLIENTES(
  NOMBRE, GENERO, EDAD, IDENTIFICACION,
  DIRECCION, TELEFONO, PASSWORD, STATUS
)
values
  (
    'Jose Lema', 'Masculino', 33, '0000-1111-22222',
    'San Pedro Sula', '3133-0501', '12345',
    true
  );

insert into CUENTAS(
  NUMERO_DE_CUENTA, ACCOUNT_TYPE, SALDO_INICIAL,
  STATUS, CLIENTE_ID
)
values
  (
    102301230, 'Savings', '600', true,
    1
  );

insert into MOVIMIENTOS(
    FECHA, VALOR, CUENTA_ID, tipo_de_movimiento
)
values
  (
  '2025-06-30', 500, 1, 'Deposito de 500'
  )
